<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.0 (Python 3.8.3 on win32)" generated="20210319 17:18:51.610" rpa="false" schemaversion="2">
<suite id="s1" name="TC1" source="C:\Users\vigne\Documents\python\Robot_Framework_Training\Testcase\TC1.robot">
<test id="s1-t1" name="LoginTest">
<kw name="Open Browser To Login Page">
<kw name="Open Browser" library="SeleniumLibrary">
<arg>${LOGIN URL}</arg>
<arg>${BROWSER}</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20210319 17:18:51.960" level="INFO">Opening browser 'gecksync.browser' to base url 'http://www.google.com'.</msg>
<kw name="Capture Page Screenshot" library="SeleniumLibrary">
<doc>Takes a screenshot of the current page and embeds it into a log file.</doc>
<msg timestamp="20210319 17:18:51.960" level="INFO">Cannot capture screenshot because no browser is open.</msg>
<status status="PASS" starttime="20210319 17:18:51.960" endtime="20210319 17:18:51.960"/>
</kw>
<msg timestamp="20210319 17:18:51.965" level="FAIL">ValueError: gecksync.browser is not a supported browser.</msg>
<status status="FAIL" starttime="20210319 17:18:51.960" endtime="20210319 17:18:51.965"/>
</kw>
<status status="FAIL" starttime="20210319 17:18:51.960" endtime="20210319 17:18:51.965"/>
</kw>
<status status="FAIL" starttime="20210319 17:18:51.960" endtime="20210319 17:18:51.965">ValueError: gecksync.browser is not a supported browser.</status>
</test>
<status status="FAIL" starttime="20210319 17:18:51.618" endtime="20210319 17:18:51.968"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="TC1">TC1</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210319 17:18:51.958" level="ERROR">Error in file 'C:\Users\vigne\Documents\python\Robot_Framework_Training\Testcase\TC1.robot' on line 3: Importing library 'gecksync' failed: ModuleNotFoundError: No module named 'gecksync'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\vigne\.virtualenvs\python-2mmW-UTN\Scripts\robot.exe
  c:\users\vigne\appdata\local\programs\python\python38-32\python38.zip
  c:\users\vigne\appdata\local\programs\python\python38-32\DLLs
  c:\users\vigne\appdata\local\programs\python\python38-32\lib
  c:\users\vigne\appdata\local\programs\python\python38-32
  c:\users\vigne\.virtualenvs\python-2mmw-utn
  c:\users\vigne\.virtualenvs\python-2mmw-utn\lib\site-packages</msg>
</errors>
</robot>
